#!/usr/bin/env python
"""
Panel Dashboard for Dust Detection results.

Architected by Aero 🍃⚡
"""

import os

import pandas as pd
import panel as pn

from dust import dust_algorithm, get_and_clean_obs
from viz import plot_dust_interactive, plot_dust_timeseries

# Enable Panel extensions
pn.extension(sizing_mode="stretch_width")


def build_dashboard(days: int = 30) -> pn.Column:
    """
    Build the dust detection dashboard for the last N days.

    Parameters
    ----------
    days : int, optional
        Number of days of data to fetch, by default 30.

    Returns
    -------
    pn.Column
        The Panel dashboard layout.
    """
    print(f"Fetching data for the last {days} days...")
    end_date = pd.Timestamp.now()
    start_date = end_date - pd.Timedelta(days=days)

    try:
        ds = get_and_clean_obs(
            source="airnow",
            start=start_date.strftime("%Y-%m-%d"),
            end=end_date.strftime("%Y-%m-%d"),
        )
    except Exception as e:
        print(f"Error fetching data: {e}")
        # Fallback to a smaller period if 30 days fails
        print("Attempting to fetch last 7 days instead...")
        start_date = end_date - pd.Timedelta(days=7)
        ds = get_and_clean_obs(
            source="airnow",
            start=start_date.strftime("%Y-%m-%d"),
            end=end_date.strftime("%Y-%m-%d"),
        )

    # Use Dask for processing
    ds = ds.chunk({"siteid": 100})

    print("Running Dust Algorithm...")
    ds = dust_algorithm(ds)

    # Compute for summary stats
    print("Computing summary statistics...")
    # Count unique site-time combinations with valid PM10 data
    # This fulfills the "unique sites in space and time" requirement
    total_obs = int(ds.PM10.notnull().sum().compute())
    has_dust_mask = ds.DUST.any(dim="time").compute()
    dust_sites = int(has_dust_mask.sum())

    print("Creating visualizations...")
    # 1. Interactive map (Track B) - Daily Max
    ds_daily = ds.resample(time="1D").max(dim="time")
    interactive_map = plot_dust_interactive(ds_daily, var="QC")

    # 2. Spaghetti Time Series plot
    # We use hourly data for the time series but only for sites that had dust
    ts_plot = plot_dust_timeseries(ds, var="PM10")

    # Summary component
    summary = pn.Column(
        pn.pane.Markdown("# 🌬️ Dust Detection Dashboard"),
        pn.pane.Markdown(
            """
            This dashboard visualizes wind-blown dust events detected by the **ASCOT**
            (Automated Surface Coordinate Observation Tracking) pipeline. ASCOT
            identifies dust by analyzing hourly PM10 concentrations and
            PM2.5/PM10 ratios, supplemented by meteorological filters.

            **Data Sources:**
            - **Air Quality:** [EPA AirNow](https://www.airnow.gov/)
            - **Meteorology:** [ISD-Lite](https://www.ncei.noaa.gov/products/land-based-station/integrated-surface-database)
              (via NOAA NCEI)
            """
        ),
        pn.pane.Markdown(
            f"**Monitoring Period:** {start_date.date()} to {end_date.date()}"
        ),
        pn.Row(
            pn.indicators.Number(
                name="Total Observations",
                value=total_obs,
                format="{value}",
                font_size="24pt",
            ),
            pn.indicators.Number(
                name="Sites with Dust Events",
                value=dust_sites,
                format="{value}",
                colors=[(0.1, "green"), (1, "red")],
                font_size="24pt",
            ),
        ),
        sizing_mode="stretch_width",
    )

    # Dashboard layout
    dashboard = pn.Column(
        summary,
        pn.pane.Markdown(
            "### Daily Max Dust Confidence (QC: 0=None, 1=Low, 2=Med, 3=High)"
        ),
        interactive_map,
        pn.pane.Markdown("### PM10 Spaghetti Plot (Sites with Detected Dust)"),
        ts_plot,
        pn.pane.Markdown("---"),
        pn.pane.Markdown("*Generated by Aero 🍃⚡ using the ASCOT Pipeline.*"),
        sizing_mode="stretch_width",
    )

    return dashboard


if __name__ == "__main__":
    # Create output directory if it doesn't exist
    os.makedirs("docs", exist_ok=True)

    print("Building dashboard...")
    # For testing, we'll use 7 days to keep it fast
    # But in the GitHub Action we can set this to 30
    days_to_run = int(os.environ.get("DASHBOARD_DAYS", 7))
    db = build_dashboard(days=days_to_run)

    output_path = "docs/index.html"
    print(f"Saving dashboard to {output_path}...")
    db.save(output_path, title="Dust Detection Dashboard", embed=True)
    print("Complete!")
